import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: [
      "tests/**/*.test.ts",
      "tests/**/*.test.tsx",
      "tests/test_*.ts",
      "tests/test_*.tsx",
      "tests/security/test_*.ts",
      "tests/dist/test_*.ts",
      "tests/safety/test_*.ts",
      "tests/pilot/test_*.ts",
      "tests/pilot/test_*.tsx",
      "tests/docs/test_*.ts",
      "tests/ux/test_*.ts",
      "tests/ux/test_*.tsx",
      "tests/ui/test_*.ts",
      "tests/ui/test_*.tsx",
      "tests/bridge/test_*.ts",
      "tests/gateway/*.test.ts",
      "tests/portal/test_*.ts",
      "tests/portal/test_*.tsx",
      "tests/beta/test_*.ts",
      "tests/beta/test_*.tsx",
      "tests/distribution/test_*.ts",
      "tests/analytics/test_*.ts",
      "tests/performance/test_*.ts",
      "tests/release/test_*.ts",
      "tests/monitoring/test_*.ts",
    ],
    exclude: [
      "**/node_modules/**",
      "**/cypress/**",
      "**/.{idea,git,cache,output,temp}/**",
      "**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*",
    ],
    environment: "node",
    css: true,
  },
});
